### PR TITLE
Return stdout, stderr from nodetool

### PR DESCRIPTION
**Pull request by thobbs**
I accidentally broke this in commit https://github.com/pcmanus/ccm/commit/10e8438c5c42d9fbbb3dcd168191a86f99fa9c70

### CODE REVIEW

**Comment by thobbs** [comment]
By the way, this is responsible for the dtest failures like this:

~~~
Traceback (most recent call last):
  File "/home/thobbs/cassandra-dtest/concurrent_schema_changes_test.py", line 147, in changes_to_different_nodes_test
    self.validate_schema_consistent(node1)
  File "/home/thobbs/cassandra-dtest/concurrent_schema_changes_test.py", line 114, in validate_schema_consistent
    response = node.nodetool('describecluster', True)[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
~~~
