### ISSUE TITLE
Cassandra compilation error

### ISSUE THREAD

**Issue by rsbarathkumar** [pcmanus/ccm#261]
Hello Scholars,
I am using Mac OSX
I have followed the steps (starting from Python installation to brew install ant). But when I tried to create Cluster, it says Cassandra compilation error. I am from mainframe back round and slowly getting used to other technologies. So as a first step to debug, I tried to uninstall Python and created cluster but the same 'Cassandra compilation error'. So my best bet is python. But I did install 64 bit python installer. Is there anything else I should know about? Please help since I am struck here in moving forward for Cassandra configurations

**Comment by ptnapoleon** [comment]
What Cassandra version are you trying to compile? What is the exact ccm command you ran? Could you paste the full stack trace from the error, please.

**Comment by rsbarathkumar** [comment]
P

**Comment by rsbarathkumar** [comment]
Hi,
Thanks for your response. Below is the command I am trying to execute and error details

Barath-Mac:~ barathkumar$ ccm create test2 -v 2.0.1
Downloading http://archive.apache.org/dist/cassandra/2.0.1/apache-cassandra-2.0.1-src.tar.gz to /var/folders/js/q164szzn1k7b82_n23md65wh0000gn/T/ccm-PrLvSA.tar.gz (10.587MB)
  11101084  [100.00%]
Extracting /var/folders/js/q164szzn1k7b82_n23md65wh0000gn/T/ccm-PrLvSA.tar.gz as version 2.0.1 ...
Compiling Cassandra 2.0.1 ...
Deleted /Users/barathkumar/.ccm/repository/2.0.1 due to error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ccm", line 4, in <module>
    __import__('pkg_resources').run_script('ccm==2.0.3.1', 'ccm')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 517, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 1443, in run_script
    exec(script_code, namespace, namespace)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ccm-2.0.3.1-py2.7.egg/EGG-INFO/scripts/ccm", line 72, in <module>
    
  File "build/bdist.macosx-10.6-intel/egg/ccmlib/cmds/cluster_cmds.py", line 127, in run
  File "build/bdist.macosx-10.6-intel/egg/ccmlib/cluster.py", line 51, in __init__
  File "build/bdist.macosx-10.6-intel/egg/ccmlib/cluster.py", line 64, in load_from_repository
  File "build/bdist.macosx-10.6-intel/egg/ccmlib/repository.py", line 40, in setup
  File "build/bdist.macosx-10.6-intel/egg/ccmlib/repository.py", line 221, in download_version
ccmlib.common.CCMError: Error compiling Cassandra. See /Users/barathkumar/.ccm/repository/last.log for details

**Comment by ptnapoleon** [comment]
Can you paste the contents of /Users/barathkumar/.ccm/repository/last.log ? That will show the compilation error

**Comment by ptnapoleon** [comment]
Off topic, 2.0.1 is a very old C* version, you may want to be looking at something > 2.0.11

**Comment by rsbarathkumar** [comment]
Hi,
sure I will compile with 2.0.11 in future. below is the log details. I believe I captured the right log. I have mentioned the command i used to retrieve the log as well.
Barath-Mac:ccm barathkumar$ cd /Users/barathkumar/.ccm/repository/
Barath-Mac:repository barathkumar$ nano last.log
Barath-Mac:repository barathkumar$ nano last.log

  GNU nano 2.0.6              File: last.log                                    

     [java] org.antlr.Tool.generateRecognizer(Tool.java:641)
     [java] org.antlr.Tool.process(Tool.java:454)
     [java] org.antlr.Tool.main(Tool.java:91)

BUILD FAILED
/Users/barathkumar/.ccm/repository/2.0.11/build.xml:233: Java returned: 1

Total time: 3 seconds
--- Cassandra Build -------------------


`ant jar` failed. Retry #1...



`ant jar` failed. Retry #2...

**Comment by rsbarathkumar** [comment]
I installed homebrew in mac and through brew install ant, I installed ant as well. Not sure why above error is coming

**Comment by ptnapoleon** [comment]
Hmm. It just appears that compilation failed with no error message. At this point, I have two suggestions: 

First, instead of installing via `ccm create test -v 2.0.11`, try `ccm create test -v binary:2.0.11`. This will install the already compiled release. If it really is just a compilation issue, this should alleviate it.

Second, if you want to get to the root of why this is happening, try cloning the Cassandra source code and building yourself. If it's some failed set up of ant, this will give a better indication of whether the issue is in ccm or not.

**Comment by rsbarathkumar** [comment]
Thank you for the suggestion and I am not at my personal computer so I will try the first option this evening.
Bear with me if I ask silly questions as I am from totally different world of mainframe and trust me I am learning fast. how do we clone the source code? do you mean to copy Cassandra version 2.0.11 source code from any location? and how do I build? If it is lot to explain some reference to documentation will really help. Thanks!

**Comment by ptnapoleon** [comment]
If you have git installed, which you can do via homebrew if you do not, it is as simple as:
`git clone http://github.com/apache/cassandra`.
This will create a cassandra/ subdirectory in your current working directory, containing the entire Cassandra source code.

Then in your terminal you can run:

```cd cassandra```
```git checkout cassandra-2.0.11```
```ant realclean; ant```

This will switch to the source code for version 2.0.11, and attempt to compile it. The output of the final `ant` command will hopefully end in `BUILD SUCCEEDED` if the compilation works.

**Comment by rsbarathkumar** [comment]
Thank you much. The Binary option to install the already compiled version created the cluster and finally I am moving forward. I will clone the Cassandra and it out to find the root cause.
One final question, should I use 'binary' going forward for nodes and cluster or any other modifications?

**Comment by ptnapoleon** [comment]
Yes, if you are only ever going to be testing with released versions, which is usually the case, using `binary` going forward when specifying the version is probably the best option.

**Comment by rsbarathkumar** [comment]
Thank you for all your help! Finally I am moving forward with Cassandra tutorial after 2 days of 'going nowhere'. Thanks again!

**Comment by d-t-w** [comment]
I had this exact issue myself recently, running `sudo ccm create..` instead completed fine, expect it may be a permissions issue after a recent OSX update.

**Comment by HemaNag** [comment]
Error while build cassandra source.

BUILD FAILED
/root/cassandra_source/cassandra/build.xml:304: Problem: failed to create task or type antlib:org.apache.maven.artifact.ant:remoteRepository
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
No types or tasks have been defined in this namespace yet

This appears to be an antlib declaration.
Action: Check that the implementing library exists in one of:
        -/usr/share/ant/lib
        -/root/.ant/lib
        -a directory added on the command line with the -lib argument
